"""
Smart Conference Badge — ESP32-WROOM-32  (no-switch version)
IEEE Rising Stars / aioble BLE firmware

Profile is loaded from profile.json on boot (generated by the web configurator).
If no profile.json is found, falls back to hardcoded defaults.

profile.json schema:
{
  "name":            "A.CHEN",
  "full_name":       "Alex Chen",
  "institution":     "MIT CSAIL",
  "info_array":      [1, 0, 1, 2, -1, -1, -1, -1, -1, -1],
  "find_this":       [1, 0, 1, 2, -1, -1, -1, -1, -1, -1],
  "match_tolerance": 1
}

Array index legend:
  [0] degree:   0=HS, 1=undergrad, 2=grad, 3=postdoc, 4=faculty, 5=industry
  [1] role:     0=attendee, 1=presenter, 2=poster, 3=chair, 4=sponsor, 5=organizer
  [2] open_to:  0=networking, 1=research, 2=internship/hiring, 3=seek mentor,
                4=offer mentor, 5=co-founder
  [3] field:    0=EE,1=CS,2=MechE,3=BioE,4=AeroE,5=MatSci,6=Physics,7=Math,
                8=ChemE,9=CogSci,10=DataSci,11=Other
  [4] method:   0=Theory,1=Sim,2=Lab,3=ML/AI,4=HW,5=SW,6=Mixed,7=Field,8=Survey
  [5] domain:   0=Robotics,1=Medical,2=Energy,3=Comms,4=Embedded,5=Autonomy,
                6=Sustainability,7=Space,8=Defense,9=Consumer
  [6] career:   0=seek intern,1=seek FT,2=hiring,3=seek PhD adv,4=seek postdoc,
                5=academia,6=industry,7=open
  [7] hw_skill: 0=PCB,1=FPGA,2=EmbeddedC,3=Python,4=MATLAB,5=ROS,6=CAD,
                7=DataPipes,8=Web,9=ML frameworks
  [8] company:  0=Boeing,1=Lockheed,2=Google,3=Microsoft,4=Apple,5=Amazon,
                6=NVIDIA,7=NASA,8=NatLab,9=Startup,10=Academia,11=Other
  [9] looking:  0=research partner,1=mentor,2=mentee,3=co-founder,
                4=collaborator,5=just talking,6=hiring,7=being hired
"""

from machine import Pin, PWM
from utime import sleep
import bluetooth
import aioble
import asyncio
import struct
import time
import urandom
import json
import sys

sys.stdout.buffer.write(b'')

# ── BLE UUIDs ──────────────────────────────────────────────────────────────────
_BADGE_SERVICE_UUID = bluetooth.UUID("6a94195c-98ff-4f26-9140-bc341ca1a88c")
_INFO_CHAR_UUID     = bluetooth.UUID("aa01b013-dcea-4880-9d89-a47e76c69c3c")
_MATCH_CHAR_UUID    = bluetooth.UUID("2aca7f5b-02b7-4232-a5f0-56cb9155be7a")

_ADV_INTERVAL_MS = 250_000

# ── Hardware pins (no-switch version) ─────────────────────────────────────────
led = Pin(2, Pin.OUT)

# Recognition LED — common-anode RGB, active LOW
red   = Pin(13, Pin.OUT)
green = Pin(33, Pin.OUT)
blue  = Pin(32, Pin.OUT)

# Proximity LED — mapped to g/y/r on pins 25/26/27
g      = PWM(Pin(25))
y      = PWM(Pin(26))
r      = PWM(Pin(27))
turnOn = Pin(14, Pin.OUT)

r.freq(1000)
g.freq(1000)
y.freq(1000)
turnOn.value(1)


# ── Recognition LED helpers ────────────────────────────────────────────────────
def led_off():
    red.value(1)
    green.value(1)
    blue.value(1)


def led_set_color(color_code):
    """Set recognition LED to a 3-bit color (1–7): bit2=R, bit1=G, bit0=B."""
    rr = (color_code >> 2) & 1
    gg = (color_code >> 1) & 1
    bb =  color_code       & 1
    red.value(  0 if rr else 1)
    green.value(0 if gg else 1)
    blue.value( 0 if bb else 1)
    turnOn.value(1)


# ── Proximity LED helpers ──────────────────────────────────────────────────────
def clamp(x, lo=0.0, hi=1.0):
    if x < lo: return lo
    if x > hi: return hi
    return x


def set_rgb(rr, gg, bb):
    """Set proximity LED; values are floats 0.0–1.0."""
    r.duty_u16(int((1 - rr) * 65535))
    g.duty_u16(int((1 - gg) * 65535))
    y.duty_u16(int((1 - bb) * 65535))


def rgb_off():
    r.duty_u16(65535)
    g.duty_u16(65535)
    y.duty_u16(65535)


def show_rssi_color(rssi, matched):
    """
    Map RSSI → red-to-green gradient on proximity LED.
    Range: -90 dBm (far, red) → -40 dBm (close, green).
    """
    if not matched:
        rgb_off()
        return
    t = clamp((rssi + 90) / 50)
    brightness = 0.2 + 0.8 * t
    set_rgb((1 - t) * brightness, t * brightness, 0)


# ── Array encoding ─────────────────────────────────────────────────────────────
def encode_array(info_list):
    fmt = "<" + "b" * len(info_list)
    return struct.pack(fmt, *[int(x) for x in info_list])


def decode_array(message):
    fmt = "<" + "b" * len(message)
    return list(struct.unpack(fmt, message))


# ── Profile loading ────────────────────────────────────────────────────────────
def load_profile():
    """
    Load badge profile from profile.json.
    Returns (info_array, find_this, match_tolerance, badge_name).
    Falls back to safe defaults if the file is missing or malformed.
    """
    try:
        with open('profile.json', 'r') as f:
            p = json.load(f)

        info = p.get('info_array',      [1, 2, 0, -1, -1, -1, -1, -1, -1, -1])
        want = p.get('find_this',       [1, 2, 0, -1, -1, -1, -1, -1, -1, -1])
        tol  = int(p.get('match_tolerance', 1))
        name = str(p.get('name', 'BADGE'))[:12]

        print(f"[profile] Loaded: {name}")
        print(f"[profile] info  = {info}")
        print(f"[profile] want  = {want}")
        print(f"[profile] tol   = {tol}")
        return info, want, tol, name

    except OSError:
        print("[profile] profile.json not found — using defaults")
    except (ValueError, KeyError) as e:
        print(f"[profile] Parse error: {e} — using defaults")

    return [1, 2, 0, -1, -1, -1, -1, -1, -1, -1], \
           [1, 2, 0, -1, -1, -1, -1, -1, -1, -1], \
           1, "BADGE"


# ── Badge class ────────────────────────────────────────────────────────────────
class Badge:

    def __init__(self, info_array, find_this, match_tolerance, name=None):
        # Config
        self.is_tracking        = False
        self.set_badgename      = name
        self.match_tolerance    = match_tolerance
        self.target_rssi        = -48
        self.timeout_s          = 10
        self.number_of_elements = 10
        self.color_set          = self._random_color()

        # Profile arrays
        self.set_info   = self._pad_array(info_array)
        self.set_target = self._pad_array(find_this)
        self.adv_name   = encode_array(self.set_info)
        self.adv_target = encode_array(self.set_target)

        # Runtime state
        self.current_rssi    = None
        self.already_connected = set()
        self.addr            = None
        self.device_addr_adv  = None
        self.device_addr_scan = None

        # BLE service + characteristics
        self.badge_service        = aioble.Service(_BADGE_SERVICE_UUID)
        self.info_characteristic  = aioble.Characteristic(
            self.badge_service, _INFO_CHAR_UUID, read=True, notify=True)
        self.match_characteristic = aioble.Characteristic(
            self.badge_service, _MATCH_CHAR_UUID, read=True, write=True)
        aioble.register_services(self.badge_service)

        # Async events
        self.connection_made       = asyncio.Event()
        self.connection_made_for_1 = asyncio.Event()
        self.stop_advertising      = asyncio.Event()
        self.search_is_going       = asyncio.Event()
        self.target_reached        = asyncio.Event()

    # ── Internal helpers ───────────────────────────────────────────────────────

    def _pad_array(self, arr):
        """Pad or truncate arr to number_of_elements, filling with -1."""
        padded = list(arr[:self.number_of_elements])
        while len(padded) < self.number_of_elements:
            padded.append(-1)
        return padded

    def _random_color(self):
        color = (urandom.getrandbits(3) % 7) + 1
        print(f"[badge] Assigned color code: {color}")
        return color

    def _extract_mac_address(self, device):
        """Parse MAC address string from an aioble device object."""
        try:
            parts = str(device).split(', ')
            if len(parts) >= 2:
                return parts[1].rstrip(')').rstrip(', CONNECTED').strip()
            else:
                print(f"[mac] Unexpected device format: {device}")
                return None
        except Exception as e:
            print(f"[mac] Extraction error: {e}")
            return None

    # ── Match logic ────────────────────────────────────────────────────────────

    def check_match(self, read_info):
        """
        Check if their info matches what we're looking for (our side of the match).
        Uses self.match_tolerance.
        """
        match    = 0
        compared = 0
        for i in range(self.number_of_elements):
            if self.set_target[i] == -1 or read_info[i] == -1:
                continue
            compared += 1
            if read_info[i] == self.set_target[i]:
                match += 1

        if compared == 0:
            print("[match] No valid fields to compare!")
            return False

        result = match >= compared - self.match_tolerance
        print(f"[match] Their side: {match}/{compared} matched → {'OK' if result else 'FAIL'}")
        return result

    def check_IAM_match(self, read_target, their_tolerance):
        """
        Check if we match what they're looking for (their side of the match).
        Uses their_tolerance from the advertisement.
        """
        match    = 0
        compared = 0
        for i in range(self.number_of_elements):
            if self.set_info[i] == -1 or read_target[i] == -1:
                continue
            compared += 1
            if read_target[i] == self.set_info[i]:
                match += 1

        if compared == 0:
            print("[match] No valid fields to compare!")
            return False

        result = match >= compared - their_tolerance
        print(f"[match] Our side: {match}/{compared} matched → {'OK' if result else 'FAIL'}")
        return result

    # ── Distance estimate ──────────────────────────────────────────────────────

    def rssi_meters(self, rssi):
        """Log-distance path loss model (RSSI_ref=-50, n=3.5). Returns float."""
        return 10 ** ((-50 - rssi) / (10 * 3.5))

    # ── Setup info dump ────────────────────────────────────────────────────────

    async def setup_task(self):
        await asyncio.sleep_ms(500)
        print(f"[setup] Badge name : {self.set_badgename}")
        print(f"[setup] info_array : {self.set_info}")
        print(f"[setup] find_this  : {self.set_target}")
        print(f"[setup] tolerance  : {self.match_tolerance}")
        led_set_color(7)
        rgb_off()
        await asyncio.sleep_ms(500)
        led_off()

    # ── Scanning ───────────────────────────────────────────────────────────────

    async def find_other(self):
        """
        Scan for compatible badges.
        Returns True on a good mutual match, or None if nothing found.
        """
        async with aioble.scan(1000, interval_us=30000, window_us=20000, active=True) as scanner:
            async for result in scanner:
                if _BADGE_SERVICE_UUID not in result.services():
                    continue

                if result.device in self.already_connected:
                    print("[scan] Already met this device, skipping")
                    await asyncio.sleep_ms(200)
                    continue

                if self.connection_made_for_1.is_set():
                    print("[scan] Already connected via advertising side")
                    await asyncio.sleep_ms(100)
                    continue

                print(f"[scan] Found: {result.name()} RSSI={result.rssi} addr={result.device}")

                if result.rssi < -100:
                    continue

                # ── Parse manufacturer data ────────────────────────────────
                try:
                    mfr_list = list(result.manufacturer(0xFFFF))
                    if not mfr_list:
                        print("[scan] Empty manufacturer data, skipping")
                        continue

                    mfr             = bytes(mfr_list[0][1])
                    is_tracking     = bool(mfr[0])
                    their_tolerance = int(mfr[1])
                    their_color     = int(mfr[2])

                    print(f"[scan] is_tracking={is_tracking}  their_tol={their_tolerance}  color={their_color}")

                    if is_tracking:
                        print("[scan] Device busy tracking, skip")
                        continue

                    n           = len(self.set_info)
                    read_info   = decode_array(mfr[3:3 + n])
                    read_target = decode_array(mfr[3 + n:3 + n + n])

                    print(f"[scan] Their info  : {read_info}")
                    print(f"[scan] Their target: {read_target}")

                except Exception as e:
                    print(f"[scan] Manufacturer data error: {e}")
                    continue

                # ── Bidirectional match check ──────────────────────────────
                if not self.check_match(read_info):
                    continue
                if not self.check_IAM_match(read_target, their_tolerance):
                    continue

                print("[scan] Mutual match! Connecting to signal them...")
                self.device_addr_scan = self._extract_mac_address(result.device)

                try:
                    connection = await result.device.connect()
                    self.color_set = their_color
                    self.connection_made.set()
                    await asyncio.sleep_ms(200)
                    await connection.disconnect()
                    await asyncio.sleep_ms(200)
                    return True

                except asyncio.TimeoutError:
                    print("[scan] Connection timeout")
                    if self.connection_made_for_1.is_set():
                        print("[scan] Advertising side already connected, continuing")
                        return True
                    self.device_addr_scan = None
                    continue

        print("[scan] Scan complete — no match found")
        return None

    # ── Advertising ────────────────────────────────────────────────────────────

    async def advertise(self):
        """
        Continuously advertise this badge's profile.
        Pauses while stop_advertising is set.
        """
        while True:
            if self.stop_advertising.is_set():
                await asyncio.sleep_ms(200)
                continue

            mfr_data = (
                struct.pack('B', int(self.is_tracking))
                + struct.pack('B', self.match_tolerance)
                + struct.pack('B', self.color_set)
                + self.adv_name
                + self.adv_target
            )

            async with await aioble.advertise(
                _ADV_INTERVAL_MS,
                name=self.set_badgename,
                services=[_BADGE_SERVICE_UUID],
                manufacturer=(0xFFFF, mfr_data),
                appearance=0,
            ) as connection:
                print(f"[adv] Connection from: {connection.device}")
                self.connection_made_for_1.set()
                self.device_addr_adv = self._extract_mac_address(connection.device)
                await connection.disconnected(timeout_ms=None)
                self.stop_advertising.set()

    # ── Address resolution ─────────────────────────────────────────────────────

    def get_address(self):
        """Return the peer MAC from whichever side completed the match first."""
        addr = self.device_addr_scan or self.device_addr_adv
        self.device_addr_scan = None
        self.device_addr_adv  = None
        return addr

    # ── Proximity feedback loop ────────────────────────────────────────────────

    async def distance_feedback_loop(self):
        """Drive the proximity LED based on live RSSI while search_is_going is set."""
        while True:
            if not self.search_is_going.is_set():
                await asyncio.sleep_ms(200)
                break

            if self.is_tracking and self.current_rssi is not None:
                rssi = self.current_rssi
                a    = 100

                led_set_color(self.color_set)
                show_rssi_color(rssi, True)

                delay = int(a * (10 ** ((-50 - rssi) / (10 * 3.5))))
                await asyncio.sleep_ms(delay)
                rgb_off()
                await asyncio.sleep_ms(delay)
            else:
                led.off()
                rgb_off()
                await asyncio.sleep_ms(100)

    # ── Proximity tracking ─────────────────────────────────────────────────────

    async def search_with_scan(self, addr):
        """
        Track a specific peer by MAC address using continuous RSSI scanning.
        Returns True when the pair physically meet (RSSI > target_rssi twice),
        or False on timeout.
        """
        self.connection_made_for_1.clear()
        self.connection_made.clear()
        self.stop_advertising.clear()

        self.search_is_going.set()
        lights_loop = asyncio.create_task(self.distance_feedback_loop())

        print(f"\n[track] Starting — target address: {addr}\n")
        start_time = time.time()

        try:
            while (time.time() - start_time) < self.timeout_s:
                target_count = 0

                try:
                    async with aioble.scan(2000, interval_us=30000, window_us=30000, active=True) as scanner:
                        async for result in scanner:
                            if _BADGE_SERVICE_UUID not in result.services():
                                continue

                            result_mac = self._extract_mac_address(result.device)

                            if result_mac != addr:
                                continue

                            self.current_rssi = result.rssi
                            self.is_tracking  = True

                            print(f"[track] RSSI={self.current_rssi}  ~{self.rssi_meters(self.current_rssi):.2f}m")

                            if self.current_rssi > self.target_rssi:
                                self.target_reached.set()
                                target_count += 1
                                print(f"[track] Close enough! ({target_count}/2)")
                                await asyncio.sleep_ms(100)

                                if target_count >= 2:
                                    # ── Successful meeting ─────────────────
                                    self.target_reached.clear()
                                    self.search_is_going.clear()

                                    print("\n[track] *** MEETING CONFIRMED ***\n")
                                    rgb_off()
                                    led_set_color(7)

                                    self.already_connected.add(result.device)
                                    await asyncio.sleep_ms(500)

                                    self.is_tracking  = False
                                    self.current_rssi = None
                                    return True

                            else:
                                target_count = 0
                                self.target_reached.clear()

                            print(f"[track] Distance: ~{self.rssi_meters(self.current_rssi):.2f}m")
                            await asyncio.sleep_ms(500)
                            break  # restart scan for fresh RSSI

                except asyncio.CancelledError:
                    print("[track] Cancelled")
                    raise

                except OSError as e:
                    print(f"[track] BLE error: {e}, retrying...")
                    await asyncio.sleep_ms(500)
                    continue

                except Exception as e:
                    print(f"[track] Unexpected error: {e}")
                    sys.print_exception(e)
                    await asyncio.sleep_ms(500)
                    continue

        except asyncio.CancelledError:
            raise

        finally:
            lights_loop.cancel()
            try:
                await lights_loop
            except asyncio.CancelledError:
                pass
            self.search_is_going.clear()
            self.is_tracking  = False
            self.current_rssi = None

        print("[track] Timed out :(")
        return False

    # ── Main run loop ──────────────────────────────────────────────────────────

    async def run_task(self):
        await self.setup_task()
        advertise_task = asyncio.create_task(self.advertise())

        while True:
            # Scan for a match
            try:
                await self.find_other()
                await asyncio.sleep_ms(100)
            except Exception as e:
                print(f"[run] find_other error: {e}")

            if not (self.connection_made.is_set() or self.connection_made_for_1.is_set()):
                continue

            addr = self.get_address()
            if addr is None:
                print("[run] No address resolved, retrying")
                continue

            self.stop_advertising.clear()
            await asyncio.sleep_ms(1500)  # let peer exit connection state

            # Track until they physically meet or time out
            met = await self.search_with_scan(addr)
            count_of_tries = 0
            while not met and count_of_tries < 5:
                print(f"[run] Retry track ({count_of_tries + 1}/5)")
                met = await self.search_with_scan(addr)
                count_of_tries += 1

            await asyncio.sleep(2)

            # Reset for next match
            self.connection_made.clear()
            self.connection_made_for_1.clear()

        await advertise_task


# ── Entry point ────────────────────────────────────────────────────────────────

async def main():
    info, want, tolerance, name = load_profile()
    badge = Badge(info, want, tolerance, name)
    await badge.run_task()


try:
    asyncio.run(main())
except KeyboardInterrupt:
    turnOn.value(0)
    led_off()
    rgb_off()
    print("[exit] Interrupted — LEDs off")
